# Modelo de seguro medico 

* usaremos idade, sexo crianças e fumante? para relacionar custos


In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [2]:
dados = pd.read_csv("../medical-insurance/data/insurance.csv")

In [3]:
#Conta os dados
dados.count()

age         1338
sex         1338
bmi         1338
children    1338
smoker      1338
region      1338
charges     1338
dtype: int64

In [4]:
# contagem de vazios
dados.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
# informações basicas como tipos de dados
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [6]:
dados.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [7]:
# visualização do inicio
dados.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# Transformaremos as categorias necessárias para numericos


In [8]:
regioes = list(dados.region.unique())
regioes
#dados.drop(["region"], axis=1, inplace=True)

['southwest', 'southeast', 'northwest', 'northeast']

In [9]:
dados["sex"] = dados["sex"].map(lambda x: 1 if x == "female" else 0 )
dados["smoker"] = dados["smoker"].map(lambda x: 1 if x == "yes" else 0)
dados["region"] = dados["region"].map(lambda x: regioes.index(x))

In [10]:
dados.head(10)

age  sex     bmi  children  smoker  region      charges
0   19    1  27.900         0       1       0  16884.92400
1   18    0  33.770         1       0       1   1725.55230
2   28    0  33.000         3       0       1   4449.46200
3   33    0  22.705         0       0       2  21984.47061
4   32    0  28.880         0       0       2   3866.85520
5   31    1  25.740         0       0       1   3756.62160
6   46    1  33.440         1       0       1   8240.58960
7   37    1  27.740         3       0       2   7281.50560
8   37    0  29.830         2       0       3   6406.41070
9   60    1  25.840         0       0       2  28923.13692

In [11]:
X = dados.iloc[:, 0:6].values
y = dados.iloc[:, 6].values


In [12]:
modelo = LinearRegression()
modelo.fit(X, y)


LinearRegression()

In [13]:
modelo.coef_
    

array([  257.28807486,   131.11057962,   332.57013224,   479.36939355,
       23820.43412267,   353.64001656])

In [14]:
modelo.intercept_

-13007.482950529971

In [15]:
modelo.score(X, y)

0.7507372027994937

In [19]:
modelo.predict([[19,1,27.900,0,1,0]])

array([25111.24186363])

In [20]:
modelo.predict([[19,1,27.900,0,0,0]])

array([1290.80774096])

# Conclusão
1. Homens custam em media menos que as mulheres e a margem aumenta em todos os casos
2. Crianças aumentam o valor do seguro em quase 500 dolares
3. A região aumenta o valor do seguro em mais de 300 dolares
4. Existem outliers na região 2